name: Node js app deploy to EKS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0' # default is latest stable
      id: install


#faz login NA REGIÃO sa-east-1 e retorna os dados da AWS - esse cara seta variavel
    - name: Configure AWS Credentials SA-EAST-1
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1
#faz login no ECR que está nessa região - esse cara usa a variavel
    - name: Login to Amazon ECR SP
      id: login-ecr-sp
      uses: aws-actions/amazon-ecr-login@v1

#O fluxo é sequencial, então primeiro pegamos a imagem e depois buildamos ela 
	#Na pratica então, primeiro logamos em são Paulo e depois logamos na gringa     

 #builda a imagem do docker - isso tá em SP
    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: hackaton
        IMAGE_TAG: 1.1
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG    
  
#para tudo  oque tá fazendo, faz login NA REGIÃO us-east-2 e 
#DEPOIS retorna os dados que a gente precisa pra poder rodar o cluster na outra região

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2


#faz login no ECR
    - name: Login to Amazon ECR EUA
      id: login-ecr-eua
      uses: aws-actions/amazon-ecr-login@v1
 #faz o update da configuração do cluster e deploya ela no EKS
    
    - name: Update kube config
      run: aws eks update-kubeconfig --name hackaton
    
    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml 
 